# openapi2-run.yaml
swagger: '2.0'
info:
  title: cmpt474-api-gateway-config The API portion of the Gateway for 474
  description: API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- http
produces:
- application/json

# FIREBASE AUTH
securityDefinitions:
    firebase:
      authorizationUrl: ""
      flow: "implicit"
      type: "oauth2"
      x-google-issuer: "https://securetoken.google.com/winter-berm-413619"
      x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
      x-google-audiences: "winter-berm-413619"

security:
  # API-level security applies to all API methods
  - firebase: [] 

paths:
  # NOTE: until there is a better way to do this
  #       we'll have to individually list each route
  # USER SERVICE ROUTES
  /accounts:
    get:
      summary: Get all accounts
      operationId: getAccounts
      x-google-backend:
        address: https://cmpt474-user-service-xvpbl7esma-uc.a.run.app/api/accounts
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '500':
          description: Something went wrong, please try again later.
          schema:
            type: string

  # POST SERVICE ROUTES
  /posts:
    get:
      summary: Get all posts
      operationId: getPosts
      x-google-backend:
        address: https://cmpt474-post-service-xvpbl7esma-uc.a.run.app/api/posts
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '500':
          description: Something went wrong, please try again later.
          schema:
            type: string
    post:
      summary: Create a new post
      operationId: createPost
      x-google-backend:
        address: https://cmpt474-post-service-xvpbl7esma-uc.a.run.app/api/posts
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
      responses:  
        '201':  
          description: Post created successfully
        '500': 
          description: Something went wrong, please try again later.
          schema:
            type: string
  
  /posts/{id}:
    get:
      summary: Get a post by id
      operationId: getPostById
      x-google-backend:
        address: https://cmpt474-post-service-xvpbl7esma-uc.a.run.app/api/posts/{id}
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The id of the post
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '500':
          description: Something went wrong, plase try again later.
          schema:
            type: string
    put:
      summary: Update a post by id
      operationId: updatePostById
      x-google-backend:
        address: https://cmpt474-post-service-xvpbl7esma-uc.a.run.app/api/posts/{id}
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The id of the post
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '500':
          description: Something went wrong, plase try again later.
          schema:
            type: string
    delete:
      summary: Delete a post by id
      operationId: deletePostById
      x-google-backend:
        address: https://cmpt474-post-service-xvpbl7esma-uc.a.run.app/api/posts/{id}
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The id of the post
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '500':
          description: Something went wrong, plase try again later.
          schema:
            type: string